name: Workflow Postman Collection with Slack Notifications

on: ['push']

jobs:
    postman-github:
      runs-on: ubuntu-latest

      steps:
        - name: Execution Postman Collection
          uses: matt-ball/newman-action@master
          with:
            apiKey: ${{ secrets.postmanApiKey }}
            collection: 19980843-e1ea76f0-dc90-4e50-9992-f68ac667e706
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependency
          run: |
            npm i  newman --location=global
            npm i  newman-reporter-allure  --location=global

        - name: Generate Allure report
          run: |
            newman run  https://api.getpostman.com/collections/19980843-e1ea76f0-dc90-4e50-9992-f68ac667e706?apikey=${{ secrets.postmanApiKey }} \
            -r allure --reporter-allure-export testArtifacts/allure.html
        # Upload the reports to TestArtifacts directory
        - name: Output the results
          uses: actions/upload-artifact@v2
          with:
            name: Reports
            path: testArtifacts